In [1]:
n = int(input())
if(n%2==0):
    print("Not wierd")
else:
    print("Wierd")

3
Wierd

In [2]:
a = int(input())
b = int(input())
print("a+b=", a+b)
print("a-b=", a-b)
print("a*b=", a*b)

3
5
a+b= 8
a-b= -2
a*b= 15

In [3]:
a = int(input())
b = int(input())
print(int(a/b))
print(float(a/b))

3
5
0
0.6

In [4]:
def is_leap(year):
    leap = False
    if(year%4==0):
        if(year%100==0):
            if(year%400==0):
                leap = True
    
    return leap

year = int(input())
print(is_leap(year))

4000
True

In [5]:
a = int(input())
str=0;
for i in range(1,a+1):
    str=str*10+i;
print(str)

5
12345

In [6]:
x, y, z, n = int(input()), int(input()), int(input()), int(input())
print ([[a,b,c] for a in range(0,x+1) for b in range(0,y+1) for c in range(0,z+1) if a + b + c != n ])

1
1
1
3
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0]]

In [8]:
if __name__ == '__main__':
    N=int(input())
    lt=list(set(map(int,input().strip().split(" "))))
    lt.sort(reverse=True)
    print (lt[1])

3
1 2 3
2

In [10]:
if __name__ == '__main__':
    n = []
    s = []
    for _ in range(int(input())):
        name = input()
        n.append(name)
        score = float(input())
        s.append(score)

    sor = list(set(s))
    sor.sort()
    sl = sor[1]
    o = []
    for x, i in enumerate(s):
        if sl == i:
            o.append(n[x])
    o.sort()
    print(*o, sep = "\n")

5
harry
50.1
berry
67.8
tina
34
tony
35
raj
51.2
tony

In [18]:
def average(a):
    return sum(a)/len(a)
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    print('%.2f'%average(student_marks[query_name]))

3
Krishna 67 68 69
Arjun 70 98 63
 Malika 52 56 60
Malika
56.00

In [16]:
N = int(input())
l = map(int, input().split())
print(hash(l))

2
1 2
-9223363288308915645